### ISSUE TITLE
Cannot install semver in Travis CI

### ISSUE THREAD

**Issue by juyeongkim** [johndharrison/semver#4]
Travis cannot compile `semver` from CRAN: https://travis-ci.org/juyeongkim/travistest/builds/194576303#L1110

**Comment by johndharrison** [comment]
Hi @juyeongkim 

semver requires C++11 support. The default linux distribution on TRAVIS uses an old version of gcc.
If you use a newer version of gcc C++11 support should be available. You can see this in the yaml file of this project https://github.com/johndharrison/semver/blob/master/.travis.yml

So adding:

dist: trusty

in your TRAVIS yaml file should solve the issue.

**Comment by juyeongkim** [comment]
@johndharrison Thank you for your prompt response. I see. I added `dist: trusty` in my Travis yaml file, and it solve the issue as you suggested. :100: https://travis-ci.org/juyeongkim/travistest/builds/194598472#L1239
