### ISSUE TITLE
Fails to compile/install on vanilla R travis build

### ISSUE THREAD

**Issue by cpsievert** [johndharrison/semver#5]
I'd like to suggest RSelenium in plotly, but this may prevent me from doing so...

https://travis-ci.org/cpsievert/semverTest#L1117-L1168

**Comment by johndharrison** [comment]
Hi Carson, semver requires c++11 support. The default linux install on travis outdated. You can request a more uptodate version in the yaml file see https://github.com/johndharrison/semver/blob/682141d686f571bc4a2c59052a150876026be216/.travis.yml#L1 in this project for example. 
Adding

dist: trusty

to the yaml should require TRAVIS to use ubuntu 14,.04

**Comment by cpsievert** [comment]
Ahh, good to know, thanks John!
